---
- name: Unzip the package downloaded from Artfactory (RedHat family)
  unarchive:
    src: '{{ directory }}/{{ zip }}'
    dest: /usr/share/nginx/html
    remote_src: yes
  when: ansible_distribution == "Amazon"

- name: Unzip the package downloaded from Artfactory (Debian family)
  unarchive:
    src: '{{ directory }}/{{ zip }}'
    dest: /var/www/html/
    remote_src: yes
  when: ansible_os_family == "Debian"
